### ISSUE TITLE
h264

### ISSUE THREAD

**Issue by XxPoNaGeXx** [mixer/obs-studio-ftl#104]
Please add the H264 encoder as I can't stream using the other one. It lags my PC out

**Comment by JimmyMac3** [comment]
In OBS-FTL the encoder is called x264 - which is the encoder that encodes in the H264 format - If your having an issue streaming it may be something else on your PC not the encoder - Maybe post your PC specs and OBS settings and the community can help fix any problems your having

**Comment by XxPoNaGeXx** [comment]
I would like to use the encoder in the image below: 

![image](https://user-images.githubusercontent.com/18231531/27689751-1b88f4f4-5cd7-11e7-9e28-d797cb8e7f8e.png) This encoder uses my GFX card as my CPU is bad. My PC sepcs are below as  well: 

![image](https://user-images.githubusercontent.com/18231531/27689819-60f2d73a-5cd7-11e7-8a53-d6d9e9e50291.png)

My CPU is 3.60 GHz

**Comment by JimmyMac3** [comment]
There have been issues in the past with FTL not working with the AMD AMF encoder and most likely isn't included in the OBS-FTL release anymore for that reason. 

I see your running an AMD APU - not an actual graphics card in a PCIE slot - That makes the video and cpu a bit under powered and can cause issues - What are your streaming settings in OBS-FTL? (Output and Video tab) - Maybe we can find the settings that are the "sweet spot" for your PC that will work without the "Lag out" issue.

P.S. - I assume from your screenshot you have OBS-Studio and OBS-FTL both installed at the same time - Although they both install in different folders on the hard drive they share the same data and if you run OBS-FTL after running OBS-Studio the settings can get messed up. Be sure to check all the settings in OBS-FTL and press apply on each tab even if you don't see anything wrong in order to re-save the settings data. If Apply is grayed out make a change and then change it back so you can re-save settings. I have seen this cause 100% CPU usage with OBS-FTL for no apparent reason.

**Comment by XxPoNaGeXx** [comment]
I do have a graphics card. It's the AMD R7 360 X OC, I just have an APU as I bought a GFX card recently but that's awesome, I'll just stick with non FTL for now

**Comment by canyougeek** [comment]
you can try using this process. I've heard a few people have had success some not. 
https://www.reddit.com/r/Amd/comments/4vbgeq/amd_vce_media_framework_support_for_obs_studio/ 
you have to copy/install the codec to the FTL folder for obs.
