### ISSUE TITLE
Thread 53c crashing

### ISSUE THREAD

**Issue by TheFluffyMarshmallow** [mixer/obs-studio-ftl#105]
for the past month ive been having an issue with obs-studio when i launch it it tells me that obs has crashed and that vcruntime is missing and i have installed the latest version of the c++ program but i still get the issue please help me here is the crash report
https://pastebin.com/HyWEj73x

**Comment by JimmyMac3** [comment]
The LATEST one won't help you need the CORRECT one
https://www.microsoft.com/en-us/download/details.aspx?id=48145

Download and install both 32 and 64 bit. Problem solved

**Comment by JimmyMac3** [comment]
Oh are you trying to install the Websocket remote plugin? it won't work with OBS-FTL at all - The Mixer Devs compiled OBS-FTL with the latest version of QuickTime - but the actual OBS project is still being compiled with QT 5.7  Not QT 5.8 or 5.9 and the plugins are written based on QT 5.7 for that reason - Until the Devs figure out their mistake and fix it (recompile with the correct QT 5.7) or someone else who knows what they are doing recompiles it correctly and makes it available to us there is no way to get that or any other plugin that uses QT to work with the FTL version

**Comment by JimmyMac3** [comment]
I have been trying to get someone to fix this for quite a while now - I hoped when I saw this it would help but NO :( 

https://github.com/dorianmuthig/obs-studio-ftl/releases - Dorian recompliled OBS-FTL with OBS-Studio 19.0.2 but he used an even later version (QT 5.9) instead of using the version (QT 5.8) the Mixer devs used or the OBS project Devs used (OT 5.7) so plugins are still broke

But I will say I have been using OBS-FTL 19.0.2-FTL 0.9.4 for a month now and it works great

**Comment by Maximilian-Reuter** [comment]
First of all, with the latest release this issue should be gone. Secondly it is QT not quick time, it has nothing to do with guick time  :P
