### ISSUE TITLE
My stream is pixelated, even my web cam is going pixelated.

### ISSUE THREAD

**Issue by PaxTG** [mixer/obs-studio-ftl#49]
I really don`t know what to do right now. Here is my log file
I don`t know what to do ringt now. 
I have tried all kind of settings but nothing worked for me.
I am curently using standard settings for obs-studio-Ftl, the recommended settings.
[2016-12-24 15-59-17.txt](https://github.com/WatchBeam/obs-studio-ftl/files/671803/2016-12-24.15-59-17.txt)

**Comment by Maximilian-Reuter** [comment]
Only thing fishy I can see is the keyframe interval of 90 i'd change that to 2 or 3

**Comment by sslivins** [comment]
no, 90 is fine, obs logs the key frame interval in frames but in the UI it's seconds

**Comment by sslivins** [comment]
i checked out your vod, i can definitely see the problem on the one from 3 days ago (dec 23rd).  but not on the one from today (dec 26th).  Im curious about this issue because it looked like a problem with rtp packetization that i thought i had fixed (and was fixed in build ftl.22 that you were using).  have you see the problem since?
