### ISSUE TITLE
OBS FTL Browser Source option missing

### ISSUE THREAD

**Issue by NakeynEndy** [mixer/obs-studio-ftl#88]
I recently boot camped my Mac and installed OBS FTL. When creating a source there is no brower option. I've unistalled and reinstalled but the brower source never appears. Please help.

**Comment by Minolta1034** [comment]
I am also having this issue.

**Comment by Minolta1034** [comment]
UPDATE: My issue was that I did not have the 2013 version of MS C++ files installed on my computer. I was directed to the 2015 (v14.0.23026) version which is required for the main OBS program. 

However it appears that BrowserSource relies on an older version of the C++ dist from 2013 (v12.0.30501) so that needs to be installed as well. Once that was done I had BrowserSource as an option and it works flawlessly.

PROTIP: You need both the x64 and x86 versions of C++ installed in order for OBS to work right.

**Comment by sdwrage** [comment]
I recently had this problem via the installer on osx. I ended up copying the SO file and the CEL file with it over to inside the apps contents and placed it in the plugin folder.
